[alias]
scaffold = "run --quiet --release -- scaffold"
download = "run --quiet --release -- download"
read = "run --quiet --release -- read"

solve = "run --release -- solve"
all = "run --release -- all"
